### ISSUE TITLE
High latency during streaming

### ISSUE THREAD

**Issue by fcagnetta** [ortclib/ortclib-sdk#10]
Hello there,

I'm using PeerCC to communicate with audio and video between an Hololens and a PC.
The issue is the extreme lag that affects the communication, even if I am streming video from Holo to PC only.

Do you experience the same? Any suggestion to improve this?

**Comment by jamescadd** [comment]
Hi - could you let me know which branch you're using and if this is in release mode?  There is further work underway to optimize the rendering but others have reported that the current solution is good enough for their purposes.

**Comment by fcagnetta** [comment]
Hi James,

I am using the branch Mosa/20180320-peercc-unity in debug mode. Release mode is currently not working, it looks like there is an unhandled exception which causes the app to crash, while in debug mode it works correctly.

**Comment by jamescadd** [comment]
Ok, the poor perf in Debug is not entirely unexpected.  We should probably troubleshoot the exception in Release mode as that's what you would want to run.

**Comment by fcagnetta** [comment]
Hi James, the exception is:

DllNotFoundException: Unable to load DLL 'MediaEngineUWP': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

raised by ControlScript.Plugin.CreateRemoteMediaPlayback() in OnEnable().

**Comment by jamescadd** [comment]
I just cloned the latest and was able to build/run in release mode on the device.  Not sure why you're seeing this error - any changes to the project that could be causing it?

**Comment by fcagnetta** [comment]
Just did it again on a different machine and got the same behaviour. I didn't change anything in the project. I really can't figure out why.

**Comment by jamescadd** [comment]
@morosev Do you have any insight?  Maybe something's missing from the Unity install?

**Comment by morosev** [comment]
The stream latency could be caused by Debug build. Streaming performances are slightly worse when debug library is used, which is more noticeable on mobile devices like HoloLens.
The missing library problem shouldn't be related to some serious bug. Build procedure for Unity sometimes fails when build configuration was changed. We should address this issue. Please just try to do a fresh clone and try Release build on clean sources.

**Comment by zhangalex** [comment]
I encountered below exception, could you please tell me do you have any idea on this?

`Running AssemblyConverter...
9>  System.InvalidOperationException: Sequence contains no matching element
9>     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
9>     at Unity.OperationContext.SetWinRTBridge(AssemblyDefinition assembly)
9>     at Unity.CreateWinRTBridgeStep.Execute()
9>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
9>     at Unity.Operation.Execute()
9>     at Unity.Program.Main(String[] args)`

I struggled whole day on this error, but I cannot figure out what is happening.

**Comment by zhangalex** [comment]
@jamescadd   thanks in advanced, do you have any idea on this?

**Comment by jamescadd** [comment]
@zhangalex Could you try with master on this repo and let me know?  this also works around the need for the prepare script so could bypass the prepare issue for you @fcagnetta

**Comment by morosev** [comment]
@zhangalex The error comes from Unity engine. Have you checked the installed Unity Editor version. It should be: `Unity version 2017.4.1 with Windows Store .NET Scripting Backend`.

**Comment by zhangalex** [comment]
@jamescadd   Hi James, thanks. Forget to tell you that I'm using branch Mosa/20180320-peercc-unity, I'm trying to capture video & holograms on Hololens.

@morosev I will download a newer Unity editor, thanks.

**Comment by jamescadd** [comment]
@fcagnetta @zhangalex Are you still experiencing latency issues?

**Comment by fcagnetta** [comment]
Hi @jamescadd no, I got a nice result in terms of latency and stability of the call. 

Btw (it would be a different issue) I can no longer see holograms in the PC, but only Hololens cam. I can't understand why.

**Comment by jamescadd** [comment]
@fcagnetta is the holograms issue in the peercc sample or in your code?  to get these to display on pc you need to enable mixed-reality capture which you can see in ControlScript.cs in the sample.

**Comment by fcagnetta** [comment]
@jamescadd sorry for the late reply. I can't find this setting in the script.

**Comment by jamescadd** [comment]
Do a search for "MrcEnabled" and it should show up, it's on Conductor.CaptureCapability
