### ISSUE TITLE
prepare.bat not prearing x64

### ISSUE THREAD

**Issue by Wolfoso** [ortclib/ortclib-sdk#13]
Hello,

I'm trying to build the branch _20180320-peercc-unity_ but I can't seem to get past the _bin/prepare.bat_ part. After downloading everything, I run the prepare.bat and this is what I get:

```
CRITICAL ERROR: Could not generate WebRTC projects for winuwp_10 platform, x64 CPU

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                  failed
            x86                 not run
            win32               not run
=================================================
```

Here's a more detailed version with _-loglevel 4_

[Pastebin Link](https://pastebin.com/hmxbd7Lk)

Any ideas why this is happening?

**Comment by jamescadd** [comment]
Here's the error you're hitting:

You must install the "Debugging Tools for Windows" feature from the Windows 10 SDK.

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

This branch requires 16299 I believe. Let us know if this helps.

**Comment by Wolfoso** [comment]
That did the trick, I had 2 versions of the SDK and none of them were the correct ones.
Thank you!

**Comment by jamescadd** [comment]
Great, apologies for the lack of documentation!
