### ISSUE TITLE
Error during sample Unity build (PeerCC-Unity)

### ISSUE THREAD

**Issue by Wolfoso** [ortclib/ortclib-sdk#14]
> (using branch Mosa/20180320-peercc-unity)
> (downloaded using git clone --recursive -b Mosa/20180320-peercc-unity https://github.com/ortclib/ortclib-sdk.git)

Hello, after preparing and building the _WebRtcUnityD3D_ solution, I open the Sample project (`in ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\PeerCCUnity`) and get this error whenever I try building that project's solution:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\project.lock.json" -bits=32 -configuration=Release -removeDebuggableAttribute=False -uwpsdk=10.0.17134.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Release" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\Assembly-CSharp.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.TilemapModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.TextRenderingModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.TerrainPhysicsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UIElementsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.TerrainModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.SpriteMaskModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.SharedInternalsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.StyleSheetsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.SpriteShapeModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UIModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.VRModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.VideoModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.VehiclesModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.WindModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.WebModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityWebRequestWWWModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityConnectModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityAnalyticsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UNETModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityWebRequestTextureModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityWebRequestModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UnityWebRequestAudioModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ScreenCaptureModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ClothModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.AudioModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.AssetBundleModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.DirectorModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.CrashReportingModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.CoreModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ARModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.AnimationModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.AIModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.AccessibilityModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ParticleSystemModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ParticlesLegacyModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.PhysicsModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.Physics2DModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.PerformanceReportingModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.JSONSerializeModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.GridModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.GameCenterModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.InputModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.IMGUIModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.ImageConversionModule.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.Timeline.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\nunit.framework.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.UI.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.SpatialTracking.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.HoloLens.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.StandardEvents.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\UnityEngine.Networking.dll" "D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\PeerConnectionClientCore.dll"" exited with code 1.	PeerCCUnity	D:\test8-27-07-2018\ortclib-sdk\common\windows\samples\PeerCC\ClientUnity\Unity\Build-Desktop - original\PeerCCUnity\PeerCCUnity.csproj	433	`

I've tried re-downloading and re-building the whole git project multiple times with no success, please help!

**Comment by jamescadd** [comment]
Part of your path looks strange "Build-Desktop - original".  I don't see this in the repo: https://github.com/webrtc-uwp/PeerCC/tree/5f494a91439751902c45263b9303f77c9d772e43/ClientUnity/Unity

Any idea where that's coming from?

**Comment by Wolfoso** [comment]
Sorry for the late reply, "Build-Desktop - original" is the folder where I've built the sample project in Unity, like this:
![image](https://user-images.githubusercontent.com/4998788/43404009-c8205956-9416-11e8-8eec-eb3bf9ab866f.png)
Then I proceeded to build the solution generated and got that error.

**Comment by morosev** [comment]
Hi @Wolfoso. I checked a command line call to AssemblyConverter.exe in our build. It looks pretty much the same. There's a beginning of the call:
```
"C:\Users\moros\Repos\ortclib-sdk-m62-peercc-unity\webrtc\windows\solutions\..\..\..\common\windows\samples\PeerCC\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="C:\Users\moros\Repos\ortclib-sdk-m62-peercc-unity\common\windows\samples\PeerCC\ClientUnity\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.17134.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Debug" 
```
We use the same settings to generate VS projects from Unity Editor.
Something is definitely screwed up.
Which version of Unity Editor do you use? We test on 2017.4.1f1.

**Comment by Wolfoso** [comment]
@morosev I know right? I can't figure out what's wrong!
I'm using Unity 2017.4.1f1 as well. Something new came up today while working with a previous buildable sample I had:
After editing the scene and adding some code, I created a solution with Unity in a different folder and when I tried to build that solution I got the same exact error I showed in the original post. I then tried creating the solution _in the same folder_ I had created a buildable solution before and it worked.
Could it be something with _my_ VS?

**Comment by morosev** [comment]
Yes, something might be wrong with VS or Unity Editor. I haven't noticed such kind of problem before.

**Comment by jamescadd** [comment]
@Wolfoso Have you been able to work through this?

**Comment by Wolfoso** [comment]
@jamescadd Nope, I've been using the workaround I mentioned: building into the working-project's folder. I really have no idea what could fix this issue.

**Comment by jamescadd** [comment]
Ok, sorry we couldn't get this resolved, my best guess is you should try on a fresh machine and see if it's related to the install based on Mosa's reply.  Going to close this for now since you're not blocked, if you hit it elsewhere (or we do) let's re-open.
