### ISSUE TITLE
Generating nuget packages is broken for M66

### ISSUE THREAD

**Issue by Holo-Krzysztof** [ortclib/ortclib-sdk#17]
Using the `createNuget.bat` script does not result in much more than just copying the template .sln to another folder; the `buildWebRTC.bat` script only shows the usage because a parameter is missing (due to changes to that script I suppose).

The background is that I'd like to create my own minimal sample to play around with the library without having to fiddle with its build system whenever there are upstream changes.

Anyway, I've fixed this and it seems to build and pack just fine. Should I submit a pull request for this?

**Comment by jamescadd** [comment]
Please do submit a PR, we'll review and accept.  cc @robin-raymond @vmancic

**Comment by Holo-Krzysztof** [comment]
Here it is: https://github.com/ortclib/ortclib-scripts/pull/1

**Comment by jamescadd** [comment]
Appreciate the submission!
