### ISSUE TITLE
Invalid pointer WinRT-Information: deviceId is a required parameter

### ISSUE THREAD

**Issue by dgmann** [ortclib/ortclib-sdk#3]
When I run an application using Ortclib on a device which does not have a webcam connected, the application crashes during Ice connection with the following exception:

Microsoft C++ exception: Platform::NullReferenceException ^ at memory location 0x0821F880. HRESULT:0x80004003 Invalid pointer WinRT-Information: deviceId is a required parameter.

If I connect a webcam, everything works just fine.
I use the latest version (1.0.54.1) of the ORTC Library from nuget

**Comment by saschenjka** [comment]
I have the same exception with WebRTC 1.54.2, in `WebRTC.Initialize(this.Dispatcher);`. 
 
> Unhandled exception at 0x749608F2 in VideoConference1.exe: Microsoft C++ exception: Platform::NullReferenceException ^ at memory location 0x0D92F41C. HRESULT:0x80004003 Ungültiger Zeiger
> WinRT information: deviceId is a required parameter.

Thank you for the solution. It works, when webcam works.
