### ISSUE TITLE
ortc/services/internal/services.events.h file not found on windows build

### ISSUE THREAD

**Issue by sivareddyensurity** [ortclib/ortclib-sdk#4]
"ortc/services/internal/services.events.h"           file not found on windows build.

Is there any separate "services.events.h" file ?? or Is it automatically generated????

Please provide solution.

**Comment by robin-raymond** [comment]
This is auto generated as part of the SDK build from the zsLib.Eventing tool. This allows events that are generated inside the process to be remoted and captured using ETW using tools like Windows Event Recorder and WIndows Event Viewer.

**Comment by sivareddyensurity** [comment]
Hi robin-raymond,

 you are saying that "ortc/internal/ortc.events.h"  is automated generated file from sdk.   But I'm not getting any ortc.events.h file.   

  For this particular file building failed. 

 Please help to me build ortclib-sdk.

----------------------------------------------------------------------------------------------------------
BUILD LOG START
----------------------------------------------------------------------------------------------------------
 
Ortclib.Test @ x64 platform Release



1>------ Build started: Project: ortclib.services (ortclib.services\ortclib.services), Configuration: Release x64 ------
2>------ Build started: Project: ortclib (ortclib\ortclib), Configuration: Release x64 ------
1>services_BackOffTimer.cpp
1>services_BackOffTimerPattern.cpp
2>ortc.cpp
2>ortc_Certificate.cpp
1>..\..\..\ortc\services\cpp\services_BackOffTimer.cpp(34): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>..\..\..\ortc\services\cpp\services_BackOffTimerPattern.cpp(33): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_Cache.cpp
1>services_DNS.cpp
2>..\..\..\ortc\cpp\ortc_Certificate.cpp(35): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_DataChannel.cpp
1>..\..\..\ortc\services\cpp\services_Cache.cpp(33): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_Helper.cpp
1>..\..\..\ortc\services\cpp\services_DNS.cpp(36): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_HTTP.cpp
1>..\..\..\ortc\services\cpp\services_Helper.cpp(34): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_HTTP_WinRT.cpp
1>..\..\..\ortc\services\cpp\services_HTTP.cpp(35): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_Logger.cpp
2>..\..\..\ortc\cpp\ortc_DataChannel.cpp(36): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_DTLSTransport.cpp
1>..\..\..\ortc\services\cpp\services_HTTP_WinRT.cpp(35): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_services.cpp
1>..\..\..\ortc\services\cpp\services_Logger.cpp(33): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_STUNDiscovery.cpp
1>..\..\..\ortc\services\cpp\services_STUNDiscovery.cpp(33): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_STUNPacket.cpp
2>..\..\..\ortc\cpp\ortc.cpp(34): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_ICEGatherer.cpp
2>..\..\..\ortc\cpp\ortc_DTLSTransport.cpp(39): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
1>..\..\..\ortc\services\cpp\services_STUNPacket.cpp(36): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
2>ortc_ICEGathererRouter.cpp
1>services_STUNRequester.cpp
1>D:\sivareddy\ortclib-sdk\ortc\xplatform\ortclib-services-cpp\ortc/services/internal/services.h(67): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory (compiling source file ..\..\..\ortc\services\cpp\services_services.cpp)
1>services_STUNRequesterManager.cpp
1>..\..\..\ortc\services\cpp\services_STUNRequester.cpp(34): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>services_TURNSocket.cpp
2>..\..\..\ortc\cpp\ortc_ICEGathererRouter.cpp(34): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_ICETransport.cpp
2>..\..\..\ortc\cpp\ortc_ICEGatherer.cpp(36): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_ICETransportController.cpp
1>..\..\..\ortc\services\cpp\services_STUNRequesterManager.cpp(34): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>..\..\..\ortc\services\cpp\services_TURNSocket.cpp(35): fatal error C1083: Cannot open include file: 'ortc/services/internal/services.events.h': No such file or directory
1>Done building project "ortclib.services.vcxproj" -- FAILED.
3>------ Build started: Project: Ortc.WebRtc.Builder, Configuration: Release x64 ------
3>  [92mWebrtc build is started. It will take couple of minutes.[0m
3>  [92mWorking ...[0m
3>  [92mx64[0m
3>  [92mPlatform x64[0m
3>  Visual Studio path is "C:\Program
3>  Determining compiler options ...
3>  CPU arhitecture is x64
3>  Selected compiler option is amd64
3>  Microsoft (R) Build Engine version 14.0.25420.1
3>  Copyright (C) Microsoft Corporation. All rights reserved.
3>  
3>MSBUILD : error MSB1009: Project file does not exist.
3>  Switch: D:\sivareddy\ortclib-sdk\ortc\windows\projects\msvc\Ortc.WebRtc.Builder\..\..\..\..\..\webrtc\xplatform\webrtc\webrtcForOrtc.vs2015.sln
3>  
3>EXEC : [91mCRITICAL error : Building WebRTC projects for x64 has failed[0m
3>  
3>  
3>  [91mFAILURE: Building WebRtc library has failed[0m
3>  
3>  [93mTotal execution time: 00:00:04 (4s total)[0m
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1276,5): error MSB3073: The command "call "D:\sivareddy\ortclib-sdk\ortc\windows\projects\msvc\Ortc.WebRtc.Builder\..\..\..\..\..\bin\buildWebRTC.bat"  "D:\sivareddy\ortclib-sdk\ortc\windows\projects\msvc\Ortc.WebRtc.Builder\..\..\..\..\..\webrtc\xplatform\webrtc\webrtcForOrtc.vs2015.sln" Release x64 ortc" exited with code 255.
2>..\..\..\ortc\cpp\ortc_ICETransportController.cpp(35): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_ORTC.cpp
2>..\..\..\ortc\cpp\ortc_ICETransport.cpp(38): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPListener.cpp
2>..\..\..\ortc\cpp\ortc_ORTC.cpp(34): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPMediaEngine.cpp
2>..\..\..\ortc\cpp\ortc_RTPListener.cpp(41): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPReceiver.cpp
2>..\..\..\ortc\cpp\ortc_RTPMediaEngine.cpp(42): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPReceiverChannel.cpp
2>..\..\..\ortc\cpp\ortc_RTPReceiver.cpp(44): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPSender.cpp
2>..\..\..\ortc\cpp\ortc_RTPReceiverChannel.cpp(44): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_RTPSenderChannel.cpp
2>..\..\..\ortc\cpp\ortc_RTPSender.cpp(44): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_SCTPTransport.cpp
2>..\..\..\ortc\cpp\ortc_RTPSenderChannel.cpp(45): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_SCTPTransportListener.cpp
2>..\..\..\ortc\cpp\ortc_SCTPTransport.cpp(39): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_SRTPTransport.cpp
2>..\..\..\ortc\cpp\ortc_SCTPTransportListener.cpp(36): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>ortc_StatsReport.cpp
2>..\..\..\ortc\cpp\ortc_SRTPTransport.cpp(37): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.events.h': No such file or directory
2>..\..\..\ortc\cpp\ortc_StatsReport.cpp(35): fatal error C1083: Cannot open include file: 'ortc/internal/ortc.stats.events.h': No such file or directory
2>Done building project "ortclib.vcxproj" -- FAILED.
4>------ Build started: Project: ortclib.Test, Configuration: Release x64 ------
4>LINK : fatal error LNK1181: cannot open input file 'webrtc.lib'
4>Done building project "ortclib.Test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 4 failed, 5 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========




----------------------------------------------------------------------------------------------------------
BUILD LOG END
----------------------------------------------------------------------------------------------------------
[ortclib.Test.txt](https://github.com/ortclib/ortclib-sdk/files/1558053/ortclib.Test.txt)

**Comment by jamescadd** [comment]
@sivareddyensurity Could you let us know if this is still outstanding or if it can be closed?
