### ISSUE TITLE
(In branch Master) WebRTC invalid folder structure. ..\yasm\patched-yasm does not exist #5 

### ISSUE THREAD

**Issue by VirtualAirwaves** [ortclib/ortclib-sdk#5]
`PS C:\Users\rober\Documents\Projects\ortclib-sdk> git log`

```
commit 7f8e70f652d6315c71f3454070518494a724b73c (HEAD -> master, origin/master, origin/HEAD)
Author: Vladimir Mancic <v.mancic@gnedo.com>
Date:   Mon Jan 29 15:22:26 2018 +0100
```

```
PS C:\Users\rober\Documents\Projects\ortclib-sdk> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

When I run bin\prepare.bat

`CRITICAL ERROR: WebRTC invalid folder structure. ..\yasm\patched-yasm does not exist`

It's there:

`C:\Users\rober\Documents\Projects\ortclib-sdk\webrtc\xplatform\yasm\patched-yasm\`

I've done this successfully in the past, so I suspect a recent check in screwed up the directory structure

(It works in branch "releases/m62".)

**Comment by vmancic** [comment]
Could you please send detailed log from bin\prepare.bat (please use argument -loglevel 4).

Thanks,
Vladimir

**Comment by vmancic** [comment]
I did fresh clone of the master branch and could not reproduce this issue.
