### ISSUE TITLE
PeerCC Unity

### ISSUE THREAD

**Issue by fcagnetta** [ortclib/ortclib-sdk#9]
Hi there, this is my situation:

I would like to have a Unity PeerCC Client for Hololens and a Unity PeerCC Client for PC (both UWP) talking each other.

I have this working in Debug mode only, because in release mode the compiler can't find MediaEngineUWP.dll and I can't find out how to fix this.

Are you guys able to build in release mode?

**Comment by jamescadd** [comment]
I'm able to build in release mode - could you try with the latest and provide an update?  The PeerCC-Sample repo now has the latest Unity code and references the NuGet package so it's much quicker to build: https://github.com/webrtc-uwp/PeerCC-Sample

**Comment by fcagnetta** [comment]
@jamescadd Hi James, I tried with the new PeerCC-Sample repo, but honestly, I am not able to follow the instructions.
There are broken links in Samples chapter and so I don't have the stuff to build the following:
"Unity 3D Peer Connection Client application - build PeerConnectionClientUnity project in webrtc\windows\solutions\WebRtcUnityD3D.sln"

Am I blind and don't get something simple to do?

**Comment by jamescadd** [comment]
If the Unity project is causing issues can you check that version 4.1f is installed, and that you chose to install the .NET Scripting Backend during Unity install (or something similar)? Sorry about the broken links, I'll have to take a look at the documentation.
________________________________

**Comment by fcagnetta** [comment]
Yes, I just tried that branch on a clean machine, but still, the prepare.bat is not working :/

CRITICAL ERROR: Could not generate WebRTC projects for winuwp_10 platform, x64 CPU

FAILURE:Preparing WebRTC development environment has failed.
=======   WebRTC prepare script summary   =======
=======   platform   =========   result   =======
            arm                 not run
            x64                  failed
            x86                 not run
            win32               not run
=================================================

**Comment by jamescadd** [comment]
Please run bin\prepare.bat -logLevel 4 and post the output
________________________________

**Comment by fcagnetta** [comment]
Here it is: https://pastebin.com/hmxbd7Lk

**Comment by robin-raymond** [comment]
I see in logs:

`You must install the "Debugging Tools for Windows" feature from the Windows 10 SDK.`

**Comment by fcagnetta** [comment]
Thanks Robin, missed that x.x I'll try again

**Comment by jamescadd** [comment]
Assume this was resolved by installing the debugging tools, reopen if not.
